#+LATEX_HEADER: \usepackage{ctex}

* Games
** Say What you see
这个谷歌小游戏既练习了英语又教你如何制作有效的图像prompt. \\
[[https://artsandculture.google.com/experiment/say-what-you-see/jwG3m7wQShZngw]]

* P
在P站上，有许多适合练习英语能力的ASMR内容。这些内容不仅能提供放松的效果，还能帮助你在“愉悦”的氛围中提高英语听力和理解能力。通过反复聆听，你可以逐渐熟悉英语的发音和节奏，增强你的语言和其他敏感度。\\
在选择适合的ASMR内容时，基本关注以下几点：
1. 语速和清晰度：选择那些语速适中、发音清晰的ASMR视频或音频。
2. 词汇难度：确保内容使用的词汇和表达符合当前的学习水平，不会过于复杂。
3. 主题兴趣：选择你感兴趣的主题，这样可以保持学习的动力和兴趣。我也不知道大家是萝莉控还是抖sm什么的，所以挑选的内容偏向多元化供参考。
开始吧！以下直接站内搜索名称即可搜出。
** Seren Eros
  女王风格，抖s福利，语速较慢，没有长难句，英语难度大致B1-B2之间

** vsilvermoon
声音性感，所扮演的角色也倾向于性感，语言水平可以定位在B2至C1之间。

** sugar waifu
萝莉音，搔你耳朵，不少视频都贴心的配有字幕文本帮助你学习英语。难度大致B2到C1之间。

** SnakeySmut
标准美式，语音语速节奏把控很好，难度B2至C1之间。

** LookingForMyBlueSky
熟女风格，入坑作：4 Horny MILFs Use You For Their Pleasure（4 个饥渴的熟女利用你来取悦她们）长达1个多小时。B1-C1.

** PuppyVA
语速适中温柔，大多为聊骚枕边话，难度B2至C1之间。

** alekirser
我非常喜欢的一位，声音元气满满，语速稍微快一些但发音非常清晰，标准美式听起来非常舒服，能适配多个角色好似专业声优。难度B1-C1之间。

** feelgoodfilth
发音清晰，语句结构不复杂口语化，B1-B2。

** TheVagineWhisperer
声音低沉磁性，不少视频都是带有字幕可以辅助学习，B1-C1。

** Thedaringfriend
适合喜欢粗旷风格的女同学学英语，声音粗野内容粗野，无长难句，B1-B2。

应该还有很多优质资源，想扩展的女同学可直接在P站搜asmr for women，或audio for women，大量听力内容供你选择。

* DashPlayer
DashPlayer：英语学习者的专属视频播放器！\\
这是一款专为英语学习者设计的视频播放器，通它提供了双语字幕、按句跳转、单词翻译、可调整布局等功能。此外，DashPlayer 还集成了下载视频、生成字幕、分割长视频等工具，软件开源。

* YouGlish
这个绝对是学习外语的利器 \\
网站名称：YouGlish \\
网站目标就是帮助用户提高听力和发音能力。它提供了一个庞大的语音库，用户可以在其中搜索特定单词或短语，并获取来自YouTube中的例句。用户可以选择不同的语言和方言，并通过听力练习来提高自己的语言技能。\\


* Podcasts
想提升英语听力最好的方式就是听大量的英语（podcasts）播客节目，以下是我一直在听的优秀英语播客节目，适合各个等级学习者。

**  A.J. Hoge（初级-中级）
A.J. Hoge 是知名的英语学习播客《Effortless English》的创始人,他的播客内容都是围绕着非常基础的词汇展开，语速发音都非常友好，你完全不会感到烦躁。从油管到Spotify和Apple Podcasts都有他的号。
** Speak English With Tiffani（初级-中级）
也是一个从语速到发音都非常友好的一位老师，非常适合初学者，她主要的内容都是围绕英语学习方法以及各种英语小技巧展开，而且用词简单，你差不多掌握2000-3000基础词汇就可以听得懂很多内容。从油管到Spotify和Apple Podcasts都有她的号。

** Coffee Break English（初级-中级）
"Coffee Break English" 是为初学者和中级英语学习者设计的少数几个播客之一。每集大约15分钟，包括主持人（母语为英语的讲者）之间的对话，随后是学习特定词汇和语法点的内容。语速

** VOA Learning English（初级-中级）
美国之音（VOA）为有兴趣学习美式英语的人提供了大量播客选择。一些播客直接涉及英语学习相关的话题，如语法、发音和美国俚语。其他的则涵盖了更广泛的话题，包括健康、科学技术和美国历史。语速相对较慢，针对初级中级的学习者很友好。除了官网，你还可以在苹果podcasts上搜到。
** Podcasts in English（初级-高级）
正如其名，是一个由两位英国主持人录制的播客网站。网站非常清新简洁，在他们的网站上，你可以免费访问数百集的节目。涵盖从初学者到高级学习者的不同等级。

** English Learning for Curious Minds（中级-高级）
播客面向中高级英语学习者，通过探索我们周围世界的过去、现在和未来，提供了一种引人入胜的学习方式。这个播客在所有主要的播客平台上都可以找到，所以无论你偏好哪个平台，都应该很容易访问。你也可以直接在他们的网站上访问这个英语学习播客。所有集数都可以免费访问。

当你的英语水平达到一定高度时，你完全可以根据个人喜好选择英语播客来收听。这个阶段，你不再局限于特定的学习内容或形式，而是可以自由探索各种主题的播客，无论是科技、文化、娱乐还是其他领域。这样不仅能够在学习语言的同时获得乐趣，还能进一步拓宽知识视野，提高语言实用能力。通过这种方式，英语学习变得更加个性化和高效。以上的推荐只是针对初学者和有一定基础的同学，如果上面的内容听起来完全无压力，推荐自由探索，找到更适合自己的内容。

* 英语学习频道
** 星荣英语笔记
https://youtube.com/@xingrong-english \\
这里是【最容易坚持】【最简单易学】且【最快获得进步】的零基础英语学习课程。
博主通过单词>词组>句子的教学结构带你循序渐进完成哑巴英语到开口流利说的程度。
配合这个应用有奇效：https://earthworm.cuixueshe.com

** 英语兔
https://youtube.com/@yingyutu/featured \\
非常适合国人的英语教学频道，尤其针对应试英语考试，语法讲解的很好，简洁明了。处在高考，中考阶段的学生可以反复刷一下他的视频。

** English with Lucy
https://youtube.com/@EnglishwithLucy/featured \\
Lucy是一位来自英国的英语教师，她以清晰、友好的方式讲解英语，非常适合各个水平的英语学习者，尤其是那些对于提高英语听说读写技能感兴趣的人。

** Learn English with
http://EnglishClass101.com \\
https://youtube.com/@EnglishClass101/featured \\
频道提供了一系列旨在提高听力、口语、阅读和写作技能的视频资源。这些内容涵盖了从基础到进阶的学习材料，但总体上，频道更倾向于服务于英语学习的入门阶段。

** BBC Learning Enlish
https://youtube.com/@bbclearningenglish \\
bbc Learning English以其高质量的教学内容、专业的英语教育背景以及丰富的学习资源，成为全球英语学习者非常喜爱的学习平台之一。适合有一定基础的人磨练听力水平和写作口语。
